// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Dem_YUpm8wzC4-8PEZkQ43a_JyXa6yc',
    appId: '1:1011074403515:web:e741365be8fb36235fad9e',
    messagingSenderId: '1011074403515',
    projectId: 'akila-maths-lms',
    authDomain: 'akila-maths-lms.firebaseapp.com',
    storageBucket: 'akila-maths-lms.firebasestorage.app',
    measurementId: 'G-LGP700CBWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByLvBO3iQE4ea9gdos7ODMcz_9ixecNVc',
    appId: '1:1011074403515:android:56078339629188705fad9e',
    messagingSenderId: '1011074403515',
    projectId: 'akila-maths-lms',
    storageBucket: 'akila-maths-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHeE3RkNfabzZik5o27rvvcoY4bCsbiwU',
    appId: '1:1011074403515:ios:44ba49e6e783d3de5fad9e',
    messagingSenderId: '1011074403515',
    projectId: 'akila-maths-lms',
    storageBucket: 'akila-maths-lms.firebasestorage.app',
    iosClientId: '1011074403515-kgaq0e96oqtulmtlhnt24u89i7uvu4a8.apps.googleusercontent.com',
    iosBundleId: 'com.akilajayaweera.akilaMathsLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHeE3RkNfabzZik5o27rvvcoY4bCsbiwU',
    appId: '1:1011074403515:ios:44ba49e6e783d3de5fad9e',
    messagingSenderId: '1011074403515',
    projectId: 'akila-maths-lms',
    storageBucket: 'akila-maths-lms.firebasestorage.app',
    iosClientId: '1011074403515-kgaq0e96oqtulmtlhnt24u89i7uvu4a8.apps.googleusercontent.com',
    iosBundleId: 'com.akilajayaweera.akilaMathsLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Dem_YUpm8wzC4-8PEZkQ43a_JyXa6yc',
    appId: '1:1011074403515:web:44adbf66e23c39e45fad9e',
    messagingSenderId: '1011074403515',
    projectId: 'akila-maths-lms',
    authDomain: 'akila-maths-lms.firebaseapp.com',
    storageBucket: 'akila-maths-lms.firebasestorage.app',
    measurementId: 'G-XZL84M4GR9',
  );
}
