class FirebaseConfig {
  static const bool useMockFallback =
      true; // Allows offline/mock preview if Firebase credentials are pending

  // Replace with actual Firebase options generated by `flutterfire configure`
  static const String apiKey = "AIzaSyB0Dem_YUpm8wzC4-8PEZkQ43a_JyXa6yc";
  static const String appId = "1:1011074403515:web:e741365be8fb36235fad9e";
  static const String messagingSenderId = "1011074403515";
  static const String projectId = "akila-maths-lms";
  static const String authDomain = "akila-maths-lms.firebaseapp.com";
  static const String storageBucket = "akila-maths-lms.firebasestorage.app";

  static Map<String, String> get options => {
    'apiKey': apiKey,
    'appId': appId,
    'messagingSenderId': messagingSenderId,
    'projectId': projectId,
    'authDomain': authDomain,
    'storageBucket': storageBucket,
  };
}
